name: Test

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true

on:
    pull_request:
        branches:
            - master
jobs:
    test:
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3', '8.4', '8.5' ]
                laravel: [ '10.*', '11.*', '12.*', '13.*' ]
                operating-system:
                    - ubuntu-latest
        name: php ${{ matrix.php }} on ${{ matrix.operating-system }} using Laravel ${{ matrix.laravel }}
        runs-on: ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
            -   name: Install composer dependencies
                env:
                    COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
                run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            -   name: Run tests
                run: phpunit --configuration phpunit.xml --no-coverage
